program mybhmie_start !(INPUT=TTY,OUTPUT=TTY,TAPE5=TTY)
	use mybhmie, only: scatter
	implicit none
!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!	CALLBH CALCULATES THE SIZE PARAMETER (X) AND RELATIVE
!	REFRACTIVE INDEX (REFREL) FOR A GIVEN SPHERE REFRACTIVE
!	INDEX, MEDIUM REFRACTIVE INDEX, RADIUS, AND FREE SPACE
!	WAVELENGTH. IT THEN CALLS BHMIE, THE SUBROUTINE THAT COMPUTES
!	AMPLITUDE SCATTERING MATRIX ELEMENTS AND EFFICIENCIES
!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

! Type declarations
	double precision, parameter :: PII = 4.0D0 * atan(1.0d0)  ! Obtain pi

!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!	NANG = NUMBER OF ANGLES BETWEEN 0 AND 180 DEGREES
!	MATRIX ELEMENTS CALCULATED AT NANG ANGLES
!	INCLUDING 0, AND 180 DEGREES
!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	INTEGER, PARAMETER :: NANG = 21

	double precision :: S_ANGLES(NANG)
	COMPLEX :: REFREL, S1(NANG), S2(NANG)
	REAL :: REFMED, REFRE, REFIM, RAD, WAVEL, X
	INTEGER :: J
! Finish type declarations
	WRITE (6,11) ! init message

! Init scattering angles
	call initParameters()
	call initScatAngles(S_ANGLES)

	WRITE (6,*) "Now running scatter subroutine"
	CALL scatter(X,REFREL,S_ANGLES,S1,S2)

!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!	PRINT S1 AND S2
!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	WRITE (6,18)
	DO 356 J=1,NANG
356 WRITE (6,76) S1(J), S2(J)

!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!	FORMATTING STATEMENTS:
!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
11	FORMAT (/"SPHERE SCATTERING PROGRAM"//)
18	FORMAT (//,9X,"S1 (RE + IM i)",24X,"S2 (RE + IM i)"//)
76	FORMAT (1X,E17.10," +",E17.10," i",7X,E17.10," +",E17.10," i")
	STOP


contains

subroutine initScatAngles (S_ANGLES)

	double precision, intent(out) :: S_ANGLES(:)

	double precision :: DANG
	integer :: J, NANG

! Finish declarations

	NANG = SIZE(S_ANGLES)
	DANG = PII / dble(NANG - 1) 
	do J = 1, NANG
		S_ANGLES(J) = dble(J-1) * DANG 
	enddo
	
end subroutine

subroutine initParameters ()
	
!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!	REFMED = (REAL) REFRACTIVE INDEX OF SURROUNDING MEDIUM
!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	REFMED = 1.0
!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!	REFRACTIVE INDEX OF SPHERE = REFRE + i*REFIM
!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	REFRE = 1.55
	REFIM = 0.0
	REFREL = CMPLX(REFRE,REFIM)/REFMED
	WRITE (6,12) REFMED, REFRE, REFIM
!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
!	RADIUS (RAD) AND WAVELENGTH (WAVEL) SAME UNITS
!	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	RAD=0.525
	WAVEL=0.6328
	X=2.*3.14159265*RAD*REFMED/WAVEL
	WRITE (6,13) RAD,WAVEL
	WRITE (6,14) X

12	FORMAT (5X,"REFMED = ",F8.4,3X,"REFRE = ",E14.6,3X,"REFIM = ",E14.6)
13	FORMAT (5X,"SPHERE RADIUS = ",F7.3,3X,"WAVELENGTH = ", F7.4)
14	FORMAT (5X,"SIZE PARAMETER = ",F8.3/)

end subroutine initParameters

end program mybhmie_start













! EOF
